parameters:
  router.request_context.host: "localhost"
  router.request_context.scheme: "http"
  router.request_context.base_url: ""
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Model/"
      - "../src/Kernel.php"

  Faker\Generator:
    factory: ['App\Faker\FrenchGeneratorFactory', "create"]

  App\Doctrine\EntityListener\UserListener:
    tags:
      - { name: doctrine.orm.entity_listener }

  gedmo.listener.sluggable:
    class: Gedmo\Sluggable\SluggableListener
    tags:
      - { name: doctrine.event_listener, event: "prePersist" }
      - { name: doctrine.event_listener, event: "onFlush" }
      - { name: doctrine.event_listener, event: "loadClassMetadata" }
